
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-training-githubissues-v1alpha1-githubissue
  failurePolicy: Fail
  name: vgithubissue.kb.io
  rules:
  - apiGroups:
    - training.githubissues
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - githubissues
  sideEffects: None
