apiVersion: training.githubissues/v1alpha1
kind: GithubIssue
metadata:
  name: githubissue-sample1
spec:
  # Add fields here
  repo: https://github.com/razo7/githubissues-operator
  title: K8s First Issue
  description: Hi 1