apiVersion: training.githubissues/v1alpha1
kind: GithubIssue
metadata:
  name: githubissue-sample3
spec:
  # Add fields here
  repo: razo7/githubissues-operator
  title: Second Issue
  description: Hi 2 from K8s
  labels: help wanted