apiVersion: training.githubissues/v1alpha1
kind: GithubIssue
metadata:
  name: githubissue-sample4
spec:
  # Add fields here
  repo: razo7/githubissues-operator
  title: First Issue
  description: Hi 4
  labels: documentation