# permissions for end users to view githubissues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubissue-viewer-role
rules:
- apiGroups:
  - training.githubissues
  resources:
  - githubissues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - training.githubissues
  resources:
  - githubissues/status
  verbs:
  - get
